export const PRODUCTS_ACTION_TYPES = {
  // SET_PRODUCTS_ARRAY: "products/SET_PRODUCTS_ARRAY",
  FETCH_PRODUCTS_START: "products/FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "products/FETCH_PRODUCTS_FAILED",
};
